### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by mmarroquin93** [rvera/image-picker#107]
Hi im trying to use the pluging but is not showing any image, thanks.

**Comment by Humni** [comment]
There is not enough information to resolve this or even mark it as a bug.
Please try it in a new project and give us steps to reproduce. It's still
working as far as I am aware

**Comment by aalavandhaann** [comment]
I really like your jquery component. But the problem is when I try adding the option tag dynamically to the select tag using jquery then there are not images loaded. What could be the problem here? I am iterating through a for loop creating the html tags dynamically and appending it to the select element. And then I call the $('select').imagepicker(). This approach is not showing the images at all. If I try to add the images inside the html hard-coded then it works as expected. Any ideas on how to resolve this?

Regards,

#0K

**Comment by Humni** [comment]
@aalavandhaann in version 4.0.0 the image picker will automatically update when the select options are updated. This version is scheduled for release later this month.
