### ISSUE TITLE
Image picker doesn't work in IE11

### ISSUE THREAD

**Issue by SSJGogeta** [rvera/image-picker#86]
Hello and thank you for the project.

I have created a web page which uses the multi-select image picker.
It works perfectly in every browser I have tested it in except from IE11.
Only a dropdown list appears and no images at all.
If I run the page locally I get a prompt which says "internet explorer has restricted this webpage from running scripts or activex controls". If I select "allow" everything is fine.
The uploaded page though doesn't have any prompt or anything.

Do you have any idea of how to bypass this problem?

Thank you very much in advance.

**Comment by SgtOddball** [comment]
That would more be an issue with your IE11 security settings, rather than a problem with the image picker it's self (the hint is in the 'internet explorer has restricted this webpage from running scripts or activex controls', you'd probably find that any scripts on the page don't run, not just image picker). 

Have a look into that and once you've easied up on your security settings you should find it works without issue.

**Comment by rvera** [comment]
Was thinking the same, thanks @SgtOddball
